//
//  VTimeline.h
//  TreeHacks
//
//  Created by Ankush Agrawal on 2/21/15.
//  Copyright (c) 2015 TreeHacks. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface VTimeline : NSObject

// Drawing Methods
+ (void)drawRightItemWithArtistImage: (UIImage*)artistImage imageY: (CGFloat)imageY imageSize: (CGFloat)imageSize timeText: (NSString*)timeText artistName: (NSString*)artistName;
+ (void)drawLeftItemWithArtistImage: (UIImage*)artistImage imageY: (CGFloat)imageY imageSize: (CGFloat)imageSize timeText: (NSString*)timeText artistName: (NSString*)artistName;

@end
